on:
  push:
    branches:
      - test
name: 🚀 Test website on push
jobs:
  deploy:
    name: 🎉 Deploy to test
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 🔑 Deploy via ssh
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        # SOURCE:
        REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
        TARGET: ${{ secrets.SSH_REMOTE_TARGET_TEST }}
        EXCLUDE: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          _FILES_OF_README/**
          README_LARAVEL.md
          README.md

  build: 
    needs: deploy
    name: 🛠️ Build to prodution
    runs-on: ubuntu-latest
    steps:
      - name: 🔐 Executing Commands by SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SSH_REMOTE_PORT }}
          script: |
            cd ${{ secrets.SSH_REMOTE_TARGET_TEST }}
            composer install
  